apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-registry-bouncer.fullname" . }}
  labels:
    {{- include "kube-registry-bouncer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kube-registry-bouncer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kube-registry-bouncer.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kube-registry-bouncer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KUBE_BOUNCER_REGISTRY_WHITELIST
              value: {{ .Values.config.registryWhitelist | quote }}
            - name: KUBE_BOUNCER_CERTIFICATE
              value: "/etc/kube-registry-bouncer/certs/tls.crt"
            - name: KUBE_BOUNCER_KEY
              value: "/etc/kube-registry-bouncer/certs/tls.key"
            - name: KUBE_BOUNCER_DEBUG
              value: {{ .Values.config.debug | quote }}
            - name: KUBE_BOUNCER_PORT
              value: {{ .Values.config.port | quote }}
          ports:
            - name: https
              containerPort: {{ .Values.config.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: certs
              mountPath: /etc/kube-registry-bouncer/certs
              readOnly: true
      volumes:
        - name: certs
          secret:
            {{- if .Values.tls.existingSecret }}
            secretName: {{ .Values.tls.existingSecret }}
            {{- else }}
            secretName: {{ include "kube-registry-bouncer.fullname" . }}-certs
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
