apiVersion: v1
kind: Service
metadata:
  name: kube-registry-bouncer-server
  namespace: kube-registry-bouncer-poc
spec:
  ports:
  - port: 443
    targetPort: 1323
    name: https
  selector:
    app: kube-registry-bouncer-server