apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kube-registry-bouncer-webhook
webhooks:
- name: kube-registry-bouncer-server.kube-registry-bouncer-poc.svc
  clientConfig:
    service:
      name: kube-registry-bouncer-server
      namespace: kube-registry-bouncer-poc
      path: "/validate-registry"
      port: 443
    caBundle: ${CA_BUNDLE}
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["pods"]
    scope: "Namespaced"
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values: ["kube-registry-bouncer-poc", "kube-system"]
  failurePolicy: Fail
  sideEffects: None
  admissionReviewVersions: ["v1"]
  timeoutSeconds: 5