name: release

on:
  push:
    branches:
      - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled" # To enable docker manifests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setup QEMU which is required for buildx to build multi-arch images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    
      # Login to GitHub registry to build & push to packages
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      # Sets up Go environment with specific version
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24
    
      # Runs goreleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Build docker image and push to registry
      - name: Build and push Docker images
        run: |
          docker buildx create --name mybuilder
          docker buildx use mybuilder
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/jimmyflatting/kube-registry-bouncer/kube-registry-bouncer:latest --push .
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
